### PR TITLE
change hex event_type to a useful string

### PR DESCRIPTION
**Pull request by jbrindle**

### CODE REVIEW

**Comment by ValdikSS** [comment]
Looks good, thanks!

**Comment by ValdikSS** [comment]
Could you share where did you use this script? Did you use it to repair ES1 or for other case?

**Comment by jbrindle** [comment]
I'm using it to debug secure boot in a UEFI system where I removed grub and am booting directly to a Linux UEFI image. I kept having to look up the event types to figure out the event log so I thought I'd fix it up. Thanks for merging.

**Comment by ValdikSS** [comment]
As far as I understand, this script works only for older version of TPM, 1.2. Do you still use 1.2?

**Comment by jbrindle** [comment]
I'm using it with TPM 2.0
```
[root@localhost ~]# dmesg | grep tpm
[    6.149272] tpm_tis IFX0785:00: 2.0 TPM (device-id 0x1B, rev-id 22)

[root@localhost ~]# ./binary_bios_measurements_parser/binary_bios_measurements_parser.py
Num PCR EV_type                         PCR_value                                Size Valid Data
0   0   s_ctrm_version                  e13ac00a227fbf2f4392c0b957b281fd77a425a8 280  1     b'R72\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x03\x00\x01\x00\x00\x00\x01\x00@\x08\xf1\x0cPO'
1   0   efi_platform_firmware_blob      736b70e538abd94469eaf441203af8aa9dd00645 16   0     b'\x00\xd0\x04\xff\x00\x00\x00\x00\x00p\x8a\x00\
x00\x00\x00\x00'
...
```

**Pull request merged**
